name: test if

on:
  push:
    branches: [ main ]

jobs:
  test-if:
    runs-on: ubuntu-latest
    steps:
      - name: pipe without escape
        if: |
          github.actor == 'radusuciu' &&
          github.event_name == 'push'
        run: echo "if newline with | syntax works with escape"
      - name: test startswith
        if: |
          startsWith('radu', github.actor) &&
          github.event_name == 'push'
        run: echo "startswith works"
      - name: control for pipe without escape
        if: |
          github.actor == 'notradusuciu' &&
          github.event_name == 'push'
        run: echo "if newline with | syntax works with escape"
