name: test if

on:
  push:
    branches: [ main ]

jobs:
  test-if:
    runs-on: ubuntu-latest
    steps:
      - name: The condition is true
        if: |
          github.actor == 'radusuciu' &&
          github.event_name == 'push'
        run: echo "if newline with | syntax works!"
